name    'mjanser-eclipse'
version '0.2.0'
source 'git://github.com/mjanser/puppet-eclipse.git'
author 'Martin Janser'
license 'MIT'
summary 'Install Eclipse'
description 'Install Eclipse with plugins'
project_page 'https://github.com/mjanser/puppet-eclipse.git'
dependency 'gini/archive', '>= 0.2.0'
